package com.insurance.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data

public class SignupEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    
    @NotBlank(message = "Name is mandatory")
    @Pattern(regexp = "^[a-zA-Z]+$", message = "Name must contain only letters")
    @Size(min = 2, max = 50, message = "Name must be between 2 and 50 characters")
    private String name;

    @NotBlank(message = "Phone number is mandatory")
    @Pattern(regexp = "^\\+?[0-9. ()-]{7,25}$", message = "Phone number is invalid")
    @Size(min = 10, max = 10, message = "Phone Number must be 10 characters")
    private String phoneNumber;

    @NotBlank(message = "Email ID is mandatory")
    @Email(message = "Email should be valid")
    @Size(max = 100, message = "Email must be less than or equal to 100 characters")
    private String emailId;
    
    @NotBlank(message = "Password is mandatory")
    @Size(min = 8, max = 20, message = "Password must be between 8 and 20 characters")
    @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$", 
             message = "Password must contain at least one digit, one lowercase and one uppercase letter, and one special character")
    private String password;

    // Constructors, getters, and setters (generated by lombok's @Data annotation)

    // No-args constructor for JPA
    public SignupEntity() {}

    // Constructor for creating instances with parameters
    public SignupEntity(String phoneNumber, String emailId, String password) {
        this.phoneNumber = phoneNumber;
        this.emailId = emailId;
        this.password = password;
    }

    // Getters and setters (generated by lombok's @Data annotation)

    // toString() method to display entity information
    @Override
    public String toString() {
        return "SignupEntity [id=" + id + ", phoneNumber=" + phoneNumber + ", emailId=" + emailId
                + ", password=" + password + "]";
    }
}
